<?php
/**
 * OdstepnyZavodVr
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ARES: REST API - veřejné
 *
 * REST rozhraní systému ARES
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * OdstepnyZavodVr Class Doc Comment
 *
 * @category Class
 * @description Odštěpný závod
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OdstepnyZavodVr extends DatumZapisuVymazuUdajeVr 
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'OdstepnyZavodVr';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'vedouci' => '\Swagger\Client\Model\AngazmaOsobaVr[]',
        'ostatni_skutecnosti' => '\Swagger\Client\Model\ObecnyTextVr[]',
        'cinnosti' => '\Swagger\Client\Model\CinnostiVr',
        'ico' => '\Swagger\Client\Model\IcoVr[]',
        'sidlo' => '\Swagger\Client\Model\AdresaVr[]',
        'pravni_forma' => '\Swagger\Client\Model\PravniFormaVr[]',
        'obchodni_jmeno' => '\Swagger\Client\Model\ObchodniJmenoVr[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'vedouci' => null,
        'ostatni_skutecnosti' => null,
        'cinnosti' => null,
        'ico' => null,
        'sidlo' => null,
        'pravni_forma' => null,
        'obchodni_jmeno' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes + parent::swaggerTypes();
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats + parent::swaggerFormats();
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'vedouci' => 'vedouci',
        'ostatni_skutecnosti' => 'ostatniSkutecnosti',
        'cinnosti' => 'cinnosti',
        'ico' => 'ico',
        'sidlo' => 'sidlo',
        'pravni_forma' => 'pravniForma',
        'obchodni_jmeno' => 'obchodniJmeno'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'vedouci' => 'setVedouci',
        'ostatni_skutecnosti' => 'setOstatniSkutecnosti',
        'cinnosti' => 'setCinnosti',
        'ico' => 'setIco',
        'sidlo' => 'setSidlo',
        'pravni_forma' => 'setPravniForma',
        'obchodni_jmeno' => 'setObchodniJmeno'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'vedouci' => 'getVedouci',
        'ostatni_skutecnosti' => 'getOstatniSkutecnosti',
        'cinnosti' => 'getCinnosti',
        'ico' => 'getIco',
        'sidlo' => 'getSidlo',
        'pravni_forma' => 'getPravniForma',
        'obchodni_jmeno' => 'getObchodniJmeno'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return parent::attributeMap() + self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return parent::setters() + self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return parent::getters() + self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }




    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        parent::__construct($data);

        $this->container['vedouci'] = isset($data['vedouci']) ? $data['vedouci'] : null;
        $this->container['ostatni_skutecnosti'] = isset($data['ostatni_skutecnosti']) ? $data['ostatni_skutecnosti'] : null;
        $this->container['cinnosti'] = isset($data['cinnosti']) ? $data['cinnosti'] : null;
        $this->container['ico'] = isset($data['ico']) ? $data['ico'] : null;
        $this->container['sidlo'] = isset($data['sidlo']) ? $data['sidlo'] : null;
        $this->container['pravni_forma'] = isset($data['pravni_forma']) ? $data['pravni_forma'] : null;
        $this->container['obchodni_jmeno'] = isset($data['obchodni_jmeno']) ? $data['obchodni_jmeno'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets vedouci
     *
     * @return \Swagger\Client\Model\AngazmaOsobaVr[]
     */
    public function getVedouci()
    {
        return $this->container['vedouci'];
    }

    /**
     * Sets vedouci
     *
     * @param \Swagger\Client\Model\AngazmaOsobaVr[] $vedouci vedouci
     *
     * @return $this
     */
    public function setVedouci($vedouci)
    {
        $this->container['vedouci'] = $vedouci;

        return $this;
    }

    /**
     * Gets ostatni_skutecnosti
     *
     * @return \Swagger\Client\Model\ObecnyTextVr[]
     */
    public function getOstatniSkutecnosti()
    {
        return $this->container['ostatni_skutecnosti'];
    }

    /**
     * Sets ostatni_skutecnosti
     *
     * @param \Swagger\Client\Model\ObecnyTextVr[] $ostatni_skutecnosti ostatni_skutecnosti
     *
     * @return $this
     */
    public function setOstatniSkutecnosti($ostatni_skutecnosti)
    {
        $this->container['ostatni_skutecnosti'] = $ostatni_skutecnosti;

        return $this;
    }

    /**
     * Gets cinnosti
     *
     * @return \Swagger\Client\Model\CinnostiVr
     */
    public function getCinnosti()
    {
        return $this->container['cinnosti'];
    }

    /**
     * Sets cinnosti
     *
     * @param \Swagger\Client\Model\CinnostiVr $cinnosti cinnosti
     *
     * @return $this
     */
    public function setCinnosti($cinnosti)
    {
        $this->container['cinnosti'] = $cinnosti;

        return $this;
    }

    /**
     * Gets ico
     *
     * @return \Swagger\Client\Model\IcoVr[]
     */
    public function getIco()
    {
        return $this->container['ico'];
    }

    /**
     * Sets ico
     *
     * @param \Swagger\Client\Model\IcoVr[] $ico ico
     *
     * @return $this
     */
    public function setIco($ico)
    {
        $this->container['ico'] = $ico;

        return $this;
    }

    /**
     * Gets sidlo
     *
     * @return \Swagger\Client\Model\AdresaVr[]
     */
    public function getSidlo()
    {
        return $this->container['sidlo'];
    }

    /**
     * Sets sidlo
     *
     * @param \Swagger\Client\Model\AdresaVr[] $sidlo sidlo
     *
     * @return $this
     */
    public function setSidlo($sidlo)
    {
        $this->container['sidlo'] = $sidlo;

        return $this;
    }

    /**
     * Gets pravni_forma
     *
     * @return \Swagger\Client\Model\PravniFormaVr[]
     */
    public function getPravniForma()
    {
        return $this->container['pravni_forma'];
    }

    /**
     * Sets pravni_forma
     *
     * @param \Swagger\Client\Model\PravniFormaVr[] $pravni_forma pravni_forma
     *
     * @return $this
     */
    public function setPravniForma($pravni_forma)
    {
        $this->container['pravni_forma'] = $pravni_forma;

        return $this;
    }

    /**
     * Gets obchodni_jmeno
     *
     * @return \Swagger\Client\Model\ObchodniJmenoVr[]
     */
    public function getObchodniJmeno()
    {
        return $this->container['obchodni_jmeno'];
    }

    /**
     * Sets obchodni_jmeno
     *
     * @param \Swagger\Client\Model\ObchodniJmenoVr[] $obchodni_jmeno obchodni_jmeno
     *
     * @return $this
     */
    public function setObchodniJmeno($obchodni_jmeno)
    {
        $this->container['obchodni_jmeno'] = $obchodni_jmeno;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
