<?php
/**
 * SpolecniciVr
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ARES: REST API - veřejné
 *
 * REST rozhraní systému ARES
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * SpolecniciVr Class Doc Comment
 *
 * @category Class
 * @description Společníci
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SpolecniciVr extends DatumZapisuVymazuUdajeVr 
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'SpolecniciVr';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'nazev_organu' => 'string',
        'spolecnik' => '\Swagger\Client\Model\SpolecnikVr[]',
        'spolecny_podil' => '\Swagger\Client\Model\SpolecnyPodilVr[]',
        'typ_organu' => 'string',
        'uvolneny_podil' => '\Swagger\Client\Model\UvolnenyPodilVr[]',
        'nazev' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'nazev_organu' => null,
        'spolecnik' => null,
        'spolecny_podil' => null,
        'typ_organu' => null,
        'uvolneny_podil' => null,
        'nazev' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes + parent::swaggerTypes();
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats + parent::swaggerFormats();
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'nazev_organu' => 'nazevOrganu',
        'spolecnik' => 'spolecnik',
        'spolecny_podil' => 'spolecnyPodil',
        'typ_organu' => 'typOrganu',
        'uvolneny_podil' => 'uvolnenyPodil',
        'nazev' => 'nazev'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'nazev_organu' => 'setNazevOrganu',
        'spolecnik' => 'setSpolecnik',
        'spolecny_podil' => 'setSpolecnyPodil',
        'typ_organu' => 'setTypOrganu',
        'uvolneny_podil' => 'setUvolnenyPodil',
        'nazev' => 'setNazev'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'nazev_organu' => 'getNazevOrganu',
        'spolecnik' => 'getSpolecnik',
        'spolecny_podil' => 'getSpolecnyPodil',
        'typ_organu' => 'getTypOrganu',
        'uvolneny_podil' => 'getUvolnenyPodil',
        'nazev' => 'getNazev'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return parent::attributeMap() + self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return parent::setters() + self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return parent::getters() + self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }




    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        parent::__construct($data);

        $this->container['nazev_organu'] = isset($data['nazev_organu']) ? $data['nazev_organu'] : null;
        $this->container['spolecnik'] = isset($data['spolecnik']) ? $data['spolecnik'] : null;
        $this->container['spolecny_podil'] = isset($data['spolecny_podil']) ? $data['spolecny_podil'] : null;
        $this->container['typ_organu'] = isset($data['typ_organu']) ? $data['typ_organu'] : null;
        $this->container['uvolneny_podil'] = isset($data['uvolneny_podil']) ? $data['uvolneny_podil'] : null;
        $this->container['nazev'] = isset($data['nazev']) ? $data['nazev'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets nazev_organu
     *
     * @return string
     */
    public function getNazevOrganu()
    {
        return $this->container['nazev_organu'];
    }

    /**
     * Sets nazev_organu
     *
     * @param string $nazev_organu Název orgánu - nestandardní
     *
     * @return $this
     */
    public function setNazevOrganu($nazev_organu)
    {
        $this->container['nazev_organu'] = $nazev_organu;

        return $this;
    }

    /**
     * Gets spolecnik
     *
     * @return \Swagger\Client\Model\SpolecnikVr[]
     */
    public function getSpolecnik()
    {
        return $this->container['spolecnik'];
    }

    /**
     * Sets spolecnik
     *
     * @param \Swagger\Client\Model\SpolecnikVr[] $spolecnik spolecnik
     *
     * @return $this
     */
    public function setSpolecnik($spolecnik)
    {
        $this->container['spolecnik'] = $spolecnik;

        return $this;
    }

    /**
     * Gets spolecny_podil
     *
     * @return \Swagger\Client\Model\SpolecnyPodilVr[]
     */
    public function getSpolecnyPodil()
    {
        return $this->container['spolecny_podil'];
    }

    /**
     * Sets spolecny_podil
     *
     * @param \Swagger\Client\Model\SpolecnyPodilVr[] $spolecny_podil spolecny_podil
     *
     * @return $this
     */
    public function setSpolecnyPodil($spolecny_podil)
    {
        $this->container['spolecny_podil'] = $spolecny_podil;

        return $this;
    }

    /**
     * Gets typ_organu
     *
     * @return string
     */
    public function getTypOrganu()
    {
        return $this->container['typ_organu'];
    }

    /**
     * Sets typ_organu
     *
     * @param string $typ_organu Typ orgánu - kód (ciselnikKod: TypOrganu, zdroj: vr)
     *
     * @return $this
     */
    public function setTypOrganu($typ_organu)
    {
        $this->container['typ_organu'] = $typ_organu;

        return $this;
    }

    /**
     * Gets uvolneny_podil
     *
     * @return \Swagger\Client\Model\UvolnenyPodilVr[]
     */
    public function getUvolnenyPodil()
    {
        return $this->container['uvolneny_podil'];
    }

    /**
     * Sets uvolneny_podil
     *
     * @param \Swagger\Client\Model\UvolnenyPodilVr[] $uvolneny_podil uvolneny_podil
     *
     * @return $this
     */
    public function setUvolnenyPodil($uvolneny_podil)
    {
        $this->container['uvolneny_podil'] = $uvolneny_podil;

        return $this;
    }

    /**
     * Gets nazev
     *
     * @return string
     */
    public function getNazev()
    {
        return $this->container['nazev'];
    }

    /**
     * Sets nazev
     *
     * @param string $nazev Název orgánu - nestandardní
     *
     * @return $this
     */
    public function setNazev($nazev)
    {
        $this->container['nazev'] = $nazev;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
