<?php
/**
 * ZakladniKapitalVr
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ARES: REST API - veřejné
 *
 * REST rozhraní systému ARES
 *
 * OpenAPI spec version: 1.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.58
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * ZakladniKapitalVr Class Doc Comment
 *
 * @category Class
 * @description Základní kapitál
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ZakladniKapitalVr extends DatumZapisuVymazuUdajeVr 
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ZakladniKapitalVr';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'typ_jmeni' => 'string',
        'text' => 'string',
        'vklad' => '\Swagger\Client\Model\ObnosVr',
        'splaceni' => '\Swagger\Client\Model\ObnosVr'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'typ_jmeni' => null,
        'text' => null,
        'vklad' => null,
        'splaceni' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes + parent::swaggerTypes();
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats + parent::swaggerFormats();
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'typ_jmeni' => 'typJmeni',
        'text' => 'text',
        'vklad' => 'vklad',
        'splaceni' => 'splaceni'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'typ_jmeni' => 'setTypJmeni',
        'text' => 'setText',
        'vklad' => 'setVklad',
        'splaceni' => 'setSplaceni'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'typ_jmeni' => 'getTypJmeni',
        'text' => 'getText',
        'vklad' => 'getVklad',
        'splaceni' => 'getSplaceni'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return parent::attributeMap() + self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return parent::setters() + self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return parent::getters() + self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }




    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        parent::__construct($data);

        $this->container['typ_jmeni'] = isset($data['typ_jmeni']) ? $data['typ_jmeni'] : null;
        $this->container['text'] = isset($data['text']) ? $data['text'] : null;
        $this->container['vklad'] = isset($data['vklad']) ? $data['vklad'] : null;
        $this->container['splaceni'] = isset($data['splaceni']) ? $data['splaceni'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets typ_jmeni
     *
     * @return string
     */
    public function getTypJmeni()
    {
        return $this->container['typ_jmeni'];
    }

    /**
     * Sets typ_jmeni
     *
     * @param string $typ_jmeni Typ jmění - kód (ciselnikKod: TypJmeni)
     *
     * @return $this
     */
    public function setTypJmeni($typ_jmeni)
    {
        $this->container['typ_jmeni'] = $typ_jmeni;

        return $this;
    }

    /**
     * Gets text
     *
     * @return string
     */
    public function getText()
    {
        return $this->container['text'];
    }

    /**
     * Sets text
     *
     * @param string $text Doplňující text
     *
     * @return $this
     */
    public function setText($text)
    {
        $this->container['text'] = $text;

        return $this;
    }

    /**
     * Gets vklad
     *
     * @return \Swagger\Client\Model\ObnosVr
     */
    public function getVklad()
    {
        return $this->container['vklad'];
    }

    /**
     * Sets vklad
     *
     * @param \Swagger\Client\Model\ObnosVr $vklad vklad
     *
     * @return $this
     */
    public function setVklad($vklad)
    {
        $this->container['vklad'] = $vklad;

        return $this;
    }

    /**
     * Gets splaceni
     *
     * @return \Swagger\Client\Model\ObnosVr
     */
    public function getSplaceni()
    {
        return $this->container['splaceni'];
    }

    /**
     * Sets splaceni
     *
     * @param \Swagger\Client\Model\ObnosVr $splaceni splaceni
     *
     * @return $this
     */
    public function setSplaceni($splaceni)
    {
        $this->container['splaceni'] = $splaceni;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
